name: Regenerate Index

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    regenerate-index:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
            - name: Regenerate index
              run: |
                  python index.py
            - name: Commit index.json changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add index.json
                  git diff-index --quiet HEAD || git commit -m "Update index.json [skip ci]"
            - name: Push changes
              run: git push
